### ISSUE TITLE
[Epic] Enhancing Bedrock Abstractions

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#10869]
This is tracking the work to align our servers and SignalR client APIs with a proposed new socket abstraction. See https://github.com/aspnet/AspNetCore/issues/10308 for a detailed description (that issue was originally tracking this work before this epic was created).

New abstraction shape:

```csharp
public abstract class ConnectionContext : IAsyncDisposable
{
  // unchanged except for IAsyncDisposable base
}

public interface IConnectionListenerFactory
{
    ValueTask<IConnectionListener> BindAsync(System.Net.EndPoint endpoint, CancellationToken cancellationToken = default);
}

public interface IConnectionListener : IAsyncDisposable
{
    EndPoint EndPoint { get; }
    ValueTask<ConnectionContext> AcceptAsync(CancellationToken cancellationToken = default);
    ValueTask UnbindAsync(CancellationToken cancellationToken = default);
}

public interface IConnectionFactory
{
    ValueTask<ConnectionContext> ConnectAsync(System.Net.EndPoint endpoint, CancellationToken cancellationToken = default);
}
```

Child Items
* [x] https://github.com/aspnet/AspNetCore/issues/10308 Client/server networking abstractions (covers the server-side work)
* [x] https://github.com/aspnet/AspNetCore/issues/10872 Adopt new Bedrock abstractions in SignalR Client.
* [x] https://github.com/aspnet/AspNetCore/issues/10607 Implement IAsyncDisposable in Connection.Abstractions (a bit tangental but related enough)
* [x] https://github.com/aspnet/AspNetCore/issues/4623 Convert https connection adapter to connection middleware

**Comment by davidfowl** [comment]
If new things come up we'll file new issues.
