### ISSUE TITLE
Prepare for a 'netcoreapp3.1' TFM

### ISSUE THREAD

**Issue by dougbu** [aspnet/AspNetCore#13581]
To minimize merge conflicts from 'release/3.1' -> 'master':
1. Remove most .NET Core TFMs from our project files and replace “netcoreapp3.0” with a property defined in the root-level Directory.Build.props file. This is a purely mechanical change (especially in VS Code) but will touch hundreds of files. (There are 631 .csproj files in the AspNetCore repo.)
    - property should be named `$(DefaultNetCoreTargetFramework)` to match 'master'
2. Change our ref/ assembly generation to name the C# files *.netcoreapp.cs instead of *.netcoreapp3.0.cs. The work is mechanical but involves a couple of quick steps after updating a few lines in the MSBuild code we use to generate the ref assemblies. (There are 110 *.netcoreapp3.0.cs files in the AspNetCore repo. The .csproj files in the same directories will also be updated.)
    - update eng\scripts\GenerateReferenceAssemblies.ps1 to match 'master'
    - git rm **/*.netcoreapp3.0.cs
    - execute eng\scripts\GenerateReferenceAssemblies.ps1
3. Change our `#if NETCOREAPP3_0` checks to be `#if NETCOREAPP`. (There are 12 *.cs files in the AspNetCore repo using the 3.0 symbol.)
4. Change version prefix from alpha to preview. 

- [x] aspnet/AspNetCore (mostly done but in 'master' and aspnet/AspNetCore#13548 shows even that needs more work; must be done in 'release/3.1' as well)
- [x] aspnet/AspNetCore-Tooling
- [x] aspnet/EntityFramework6 (aspnet/EntityFramework6#1223 has this but needs more work)
- [x] aspnet/EntityFrameworkCore (aspnet/EntityFrameworkCore#17658 needs this)
- [x] aspnet/Extensions
- [x] aspnet/Blazor for the branding change only: https://github.com/aspnet/Blazor/commit/1eb0ac055727d102f9c099a7715624e3724764bf

#### Details
These changes have the added benefit of easing TFM changes e.g. adjusting to the new netcoreapp3.1 TFM but that is not the primary goal. W.r.t. merge conflicts:
1. Avoids merge conflicts as we touch nearby lines in the project files.
2. Avoids merge conflicts as ref assemblies need to be updated. Without the proposed change, the generated files won’t exist in the target repo and the files that do exist will need to be manually updated. This may be change with the largest impact.
3. Avoids merge conflicts as we touch nearby lines in the C# files.

**Comment by JunTaoLuo** [comment]
FYI, we're running into https://github.com/NuGet/Home/issues/8467 which I'm working around by specifying NoWarn. These workarounds should be removed once we have an updated SDK with the NuGet fix.

**Comment by dougbu** [comment]
@JunTaoLuo can't those issues be worked around by adding `_._` files to the .nupkg or fixing the project file?

When we saw this error before, it indicated a real problem in the Components project (which we haven't fixed): The source-built .nupkg doesn't contain the expected files because single-TFM projects don't lay out the obj/ folder with a TFM in the directories (IIRC).

**Comment by JunTaoLuo** [comment]
We can workaround NU5128 with that. Don't think that's going to help with the NU5131 issues though.

**Comment by dougbu** [comment]
Ah, right. I see others are disabling NU5131 warnings.

**Comment by JunTaoLuo** [comment]
All PRs have been merged. Follow up issues have been filed. Looking into merging 3.1 => master.
