### ISSUE TITLE
Blazor 3.1 Roadmap

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#13785]
**This is a tracking item for the overall Blazor features in .NET Core 3.1**

.NET Core 3.1 is a short quality focused release focused on fixing top customer issues with minimal feature work.

### Preview 1

- [x] [#9061](https://github.com/aspnet/AspNetCore/issues/9061) - Supporting calling non-generic instance methods on generic types
- [x] [#13291](https://github.com/aspnet/AspNetCore/issues/13291) - Update default Razor versions in VS to be 3.0
- [x] [#5487](https://github.com/aspnet/AspNetCore/issues/5487) - Components support partial classes
- [x] [#14433](https://github.com/aspnet/AspNetCore/issues/14433) - Blazor Server prerendering with parameters support

### Preview 2

- [x] [#10643](https://github.com/aspnet/AspNetCore/issues/10643) - CompareAttribute ignored with OnValidSubmit EditForm
- [x] [#9133](https://github.com/aspnet/AspNetCore/issues/9133) - VS shows documentation for attributes when writing the component tag
- [x] [#5476](https://github.com/aspnet/AspNetCore/issues/5476) - Developer exception page
- [x] [#5545](https://github.com/aspnet/AspNetCore/issues/5545) - Control over event propagation and default actions
- [x] [#13726](https://github.com/aspnet/AspNetCore/issues/13726) - Replace RenderComponentAsync in templates with a new tag helper
- [x] [#10526](https://github.com/aspnet/AspNetCore/issues/10526) - Validation doesn't automatically traverse members 

### GA

**Comment by rynowak** [comment]
We lock roadmap issues to keep the main thread clean. However, we **do** want your feedback and questions about what's going on in 3.1 Please feel free to use other issues to discuss.

**Comment by mkArtakMSFT** [comment]
Closing this as there are no more actions pending here.
