### ISSUE TITLE
Synchronize HTTP/2 Framing and HPACK code with Corefx

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#13900]
**Things to share:**
- HPACK (Encoding/Decoding), These are similar today, so it should be a simple unification
- Framing code, different representations/organization, but not a lot of code.

**Open questions:**
- Copyrights
- Namespaces
- Resource strings

**Options to share code:**
- PR bot to keep aspnetcore and corefx in sync
- Share source package from corefx that aspnetcore can consume

**Actionable items:**
- [x] Synchronize aspnetcore and corefx HPACK implementation
- [ ] Synchornize frame types
- [ ] Keep code in sync.
- [ ] Sync unit tests
- [ ] Add and sync microbenchmarks

cc @Tratcher @scalablecory @geoffkizer

**Comment by Tratcher** [comment]
Open question: Inner loop development. How can we observe/measure/test how changes to shared source impact both corefx and aspnetcore before checking in? That includes API changes, behavior changes, perf, etc..

At a minimum, shared sources should include shared unit tests. Shared micro-benchmarks would be good too.

Also, we need to set up a group of cross team code owners to review changes to the shared code.

**Comment by geoffkizer** [comment]
> Corefx internalizes these, requires a bit more work

What does this mean?

> How to actually share code:

Are these two distinct options?

**Comment by jkotalik** [comment]
> What does this mean?

In the HTTP2 implementation, we have structs which represent unique frame types: https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Frame.cs. For example, rst: https://github.com/aspnet/AspNetCore/blob/master/src/Servers/Kestrel/Core/src/Internal/Http2/Http2Frame.RstStream.cs

> Are these two distinct options?

Yes.

Updated the issue for clarity.

**Comment by jkotalik** [comment]
Closing in favor of https://github.com/dotnet/corefx/issues/41787
