### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/AspNetCore#14271]
Allow Razor documents to be properly formatted.

**Comment by ponchautf** [comment]
Hi,

Did you have any progress to share about this issue progress?

**Comment by NTaylorMullen** [comment]
> Did you have any progress to share about this issue progress?

@ponchautf  It's definitely one of the most asked for features and it's something we want to accomplish sooner rather than later. That being said we're currently prioritizing other high impact issues such as colorization over this. We're still looking at 2 or so releases out for formatting to land (a few months).

**Comment by NTaylorMullen** [comment]
@ajaybhargavb given we're not going to return to formatting (we got `@code` formatting done for those watching this comment) till post-build how do you feel about us putting this in the backlog and out of `In Progress`?

**Comment by ajaybhargavb** [comment]
Sounds good. We can backlog this until the prerequisites like https://github.com/dotnet/aspnetcore/issues/14286 are handled.

**Comment by zmp2000** [comment]
Any progress on this? On latest version we have no more "There is no formatter" message but nothing is happening!

**Comment by ajaybhargavb** [comment]
@zmp2000, we currently have support for formatting C# code inside the `@code/@functions` block. HTML formatting is not implemented yet but is definitely one of our top priorities for the near future.

**Comment by matijagrcic** [comment]
@ajaybhargavb this year?
Currently this is the sole reason using vs code for core development is unusable.  Remember that preview announcement was last year.

Will this new formatting power the VS also?

**Comment by ChristopherHaws** [comment]
Would this also include the ability to customize code style preferences like we currently can with C# in Visual Studio using the options window or .editorconfig file? If not, is there another issue tracking that?

**Comment by NTaylorMullen** [comment]
> Would this also include the ability to customize code style preferences like we currently can with C# in Visual Studio using the options window or .editorconfig file? If not, is there another issue tracking that?

What type of code styles are you interested in? I'd imagine C#'s code styles are respected today are they not?

**Comment by ChristopherHaws** [comment]
@NTaylorMullen I can think of a few use cases I would use.
- I would like to be able to have open curly braces on the same line for razor files.
- In C# we enforce the use of `this.` but might not want to for razor files since there aren't really constructors in razor files (things are injected using `@inject` instead of constructors).
- I would also like a way to enforce the casing of things that are injected using `@inject`.
- I personally like putting my `@code` blocks above the HTML markup, if this could be a preference so that new razor components were created that way would be nice too

I'm sure I could come up with others, but those are some I can think of off the top of my head :)

**Comment by NTaylorMullen** [comment]
Ah I see. So sadly this effort doesn't encompass that 😢

**Comment by nextfool** [comment]
please, is there any progress on this?

**Comment by nextfool** [comment]
> please, is there any progress on this?

I would die for having this.

**Comment by matijagrcic** [comment]
Still pretty much the same state but the language server is now available in Visual Studio https://devblogs.microsoft.com/aspnet/new-experimental-razor-editor-for-visual-studio/

**Comment by KrisPetkov** [comment]
One more like from me for this feature. Maybe it’s quite annoying for the team but this is the only reason stopping me from using VS Code as a daily driver, as I’m using Razor most of the time.

**Comment by frankhale** [comment]
I am seeing weird razor formatting issues where it's easily confused specifically about HTML style markup. Seems Visual Studio has no issues formatting. Here is a screenshot of VSCode 1.50 with the C# extension. Notice that the Razor formatting is confused about the markup:

If I remove the @foreach block the formatting is no longer confused and displays properly.

![image](https://user-images.githubusercontent.com/190154/95947702-32f79b00-0dbd-11eb-921a-047bc97419b3.png)

**Comment by ajaybhargavb** [comment]
Razor formatting in VSCode is now available with the latest C# extension (https://github.com/OmniSharp/omnisharp-vscode/releases/tag/v1.23.3).
We're still in the process of ironing out rough edges. Please try it out and provide feedback!

**Comment by ajaybhargavb** [comment]
@frankhale, I believe what you are seeing is the same issue as https://github.com/dotnet/aspnetcore/issues/26736. We're looking into fixing this.

**Comment by KrisPetkov** [comment]
@ajaybhargavb I'm with the updated VS Code 1.50 and C# Extension 1.23.3 but the formatting is not working for me at all. I haven't changed any default settings of the extension: 

![0RaY9IwMpH](https://user-images.githubusercontent.com/6774998/95957630-9955db00-0e08-11eb-946e-943b54ed46d7.gif)

**Comment by MarkusRodler** [comment]
I have the same formatting bug as already presented above. It is ok for me that it doesn't work right now. But I have a big problem with the auto-formatting on save. I can't disable it. It's running riot.

**Comment by frankhale** [comment]
@MarkusRodler I tried disabling Razor formatting but it doesn't work. The settings under preferences doesn't seem to do anything.

![image](https://user-images.githubusercontent.com/190154/95994402-3eb78180-0dfe-11eb-904f-e16198900dcc.png)

**Comment by MarkusRodler** [comment]
That was also my observation... 😢

**Comment by ponchautf** [comment]
The last version is unusable.
I got many many issue with it:

- formating not working (and when it works, not accurate at all)
- autocompletion inject irrelevant tags (I type <div> and it get replaced by <DataAnnotation>
- divs inside foreach are underlined in red (why?)
- mouse over on properties keep displaying "Loading" and nothing else
- quick navigation using cmd+click work time to time, not always (get a thin blue strip at the top of my code indicating that VS code is searching

I also requested razor formating but I prefer wait for a stable version.

Is it possible to rollback to the previous omnisharp version?, 1.23.3 it too buggy to work with it

**Comment by ajaybhargavb** [comment]
@frankhale @MarkusRodler thanks for trying it out. Something regressed in latest OmniSharp version causing our settings sync to not work. I understand this can be frustrating and we are working with OmniSharp folks [on a fix](https://github.com/OmniSharp/csharp-language-server-protocol/pull/392) and will get it resolved ASAP. In the meantime, you can disable format on save globally,
 
![image](https://user-images.githubusercontent.com/1579269/96043143-610fc600-0e23-11eb-9456-933f529beaed.png)

**Comment by ajaybhargavb** [comment]
@KrisPetkov, @ponchautf thanks for trying it out. Can you please file a separate issue with a repro to help investigate more?

**Comment by KrisPetkov** [comment]
@ajaybhargavb sorry for the late response. I will open an issue today

**Comment by frankhale** [comment]
(re: Blazor razor component formatting): On VS Code insiders I'm seeing a different behavior. Some razor components will format correctly and some (I have @if's and @foreach's) will no longer format at all. Even the @code block won't format even though format on save is turned on. The formatting chord CTRL+K, CTRL+D will not force it to format either.

**Comment by ajaybhargavb** [comment]
Lots of bug fixes as part of https://github.com/dotnet/aspnetcore/issues/26527.

Remaining known issues:
- [ ] [Unable to remap projected document edits if they fall outside of known list of source mappings](https://github.com/dotnet/aspnetcore/issues/26501)
- [ ] [Formatting C# blocks with nested HTML removes unexpected newlines](https://github.com/dotnet/aspnetcore/issues/26836)
- [ ] [Unexpected indentation for multiline expressions at the start of a Razor block](https://github.com/dotnet/aspnetcore/issues/29200)
- [ ] [@{ block format on type adds New Line on pressing ';'](https://github.com/dotnet/aspnetcore/issues/27102)
- [ ] [Razor LSP top-level implicit statements don't get formatted](https://github.com/dotnet/aspnetcore/issues/27142)

**Comment by nextfool** [comment]
so there is still no progress for this? after 3 years?....I mean, common you are Microsoft right? even .Net 5 is  released,   vs code is still not supporting razor files? Is anybody here who develop asp.net projects? how do you live with this problem? I mean, the .cshtml formatting is totally a mess.

**Comment by zmp2000** [comment]
@nextfool I totally agree, It's a mess, it gives me a headache every day! Specially with Blazor

**Comment by nextfool** [comment]
bump

**Comment by ponchautf** [comment]
**I don't think we should wait anymore for that.**
3 year and Vs Code / Omnisharp is still not able to handle razor markups.
formatting is a mess, many many errors, unstable, unusable.

A definitively give up ans switched to JetBrains rider, expensive but not that much regarding the time wasted with Vs code.

Visual studio for Mac is free but it's also the worst IDE I used
Microsoft :  please make Visual studio Mac as goo-d as Visual studio Windows (and don't try to rely/stick too much on Mac os UI : make a good IDE, not a good Mac OS IDE).

VS code i a great text editor but not more than that.
Just good enough for Javascript (and even with JS, there sometime stupid issue)

**Comment by NTaylorMullen** [comment]
Hey folks, thought I'd leave a message here and just let you all know that we're hard at work on making Razor formatting reliable, flexible, and more importantly correct 😆! Please bare with us though, it's an incredibly hard area to get right and we want to make sure we're able to deliver a quality experience for everyone to use. Love all the passion though, please keep leaving your suggestions, insight and ideas!

**Comment by vchirikov** [comment]
![image](https://user-images.githubusercontent.com/40987940/135335668-5557bd06-baef-42d7-a99b-9874162e15a0.png)

**Comment by NTaylorMullen** [comment]
lol ya it's been a while. I'd be super curious as to all of your thoughts on Razor formatting in the latest [Visual Studio 2022 builds](https://visualstudio.microsoft.com/vs/preview/). We've done loadsssss of work in  the area!

/cc @davidwengier
