### ISSUE TITLE
[EPIC]: Bedrock Endgame

### ISSUE THREAD

**Issue by davidfowl** [aspnet/AspNetCore#15005]
- [ ] - Non-HTTP TLS connection middleware https://github.com/aspnet/AspNetCore/issues/12809
- [ ] - Introduce new Server API decoupled from Kestrel (issue TBD)
- [ ] - Introduce new Client API for building a middleware pipeline (issue TBD)
- [ ] - Generic Host integration (TBD)
- [ ] - Support Windows NamedPipe's in bedrock https://github.com/aspnet/AspNetCore/issues/14207
- [ ] -

**Comment by shaggygi** [comment]
Some of these might be able to check off or update?  For example, "Introduce new Server API"?

**Comment by Xyncgas** [comment]
why doesn't microsoft hire another 50 people to work on this which is used by millions of people

**Comment by Xyncgas** [comment]
or go to church and ask some of the folks whom retired from their fortran from the last century to volunteer to work on this project, it's like a toy for them

**Comment by davidfowl** [comment]
Did you add your upvote? There's a sense that this is needed from the team but it would help if people upvoted and shared their use cases. I think this is a big missing piece from the .NET ecosystem and it's why I keep https://github.com/davidfowl/Bedrockframework alive

**Comment by shaggygi** [comment]
Another standup update on topic along with status of System.IO.Connections would be nice 😄

**Comment by rwkarg** [comment]
We have several legacy and third party custom TCP implementations that we integrate with and piping our own serialization in to the existing routing/controller infrastructure would simplify and consolidate a good amount of our implementations. 

It would also be nice to be able to take messages from a RabbitMQ or Kafka consumer, route by the payload to an action, then return a message result to drive ack/nack actions or advance offsets.

**Comment by davidfowl** [comment]
We've evolved the stack to support writing low level networking code via connection abstractions and various transports offered on top of kestrel. I'm closing this issue out as there's no specfic work item it's covering (there are other linked issues).

> It would also be nice to be able to take messages from a RabbitMQ or Kafka consumer, route by the payload to an action, then return a message result to drive ack/nack actions or advance offsets.

That's not this issue, this is extremely low level networking (for which a library that handle those protocols can be written on top of).
