### ISSUE TITLE
Blazor 0.7.0 release checklist

### ISSUE THREAD

**Issue by danroth27** [aspnet/AspNetCore#15470]
- [x] Update survey links in templates
- [x] Create final release build with correct version numbers
- [x] Perform final manual verification of VSIX/packages, including that they are all signed
- [x] Upload packages to nuget.org
- [x] Upload VSIX to VS marketplace
- [x] Wait for nuget.org to re-index and show new package versions
- [x] Publish updated docs (conceptual and API)
- [x] Create release tag and release on the Blazor repo
- [x] Publish announcement blog post
- [x] Tweet announcement from aspnet account
- [x] Mark the release's milestone as done
