### ISSUE TITLE
Add first class support for onclick and other event handlers

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#16244]
## What is it?

We're doing some tweaks to the ways that event handlers get wired to DOM events in Blazor, and adding a lot more features and power.

Hooking up a C# function to a handle a DOM event will look like:
```
<button onclick="@OnClick" />
@functions {
    void OnClick(UIMouseEventArgs e)
    {
        Console.WriteLine("hello, world");
    }
} 
```

or if you'd prefer a lambda:
```
<button onclick="@(e => Console.WriteLine("hello, world"))"
```

This has first class integration with the editor in Visual Studio and will include tooltips and completion.

Passing in a string like `<button onclick="foo" />` will not do any magic, and will work as if it were normal HTML.

## What's changing

This kind of thing has been possible today using a few temporary syntaxes that will be removed as part of 0.2. Namely `<button @onclick(Foo) />`  and `<button onclick=@{ Foo(); } />. This change makes the event handler wire up look and function the same way as other Razor features.

## What's added

Along with this change we'll be defining more of the standard DOM events with first class completion and eventargs types.

We'll also be adding support for *arbitrary event names*. So `<button onfoo="@Foo" />` will bind the Foo method to be called when the `foo` DOM event is fired.

## TODO
- [x] Add language support for `onclick` and `onchange`
- [x] Remove temporary workarounds
- [x] Support `Action` in addition to `UIEventHandler`
- [x] Add support for arbitrary events
- [x] Remove allocations for common cases
