### ISSUE TITLE
0.1.0 release tasks checklist

### ISSUE THREAD

**Issue by SteveSandersonMS** [aspnet/AspNetCore#16393]
- [x] Blog post - @danroth27 
- [x] Verification: installation steps, follow tutorial in blog post - @kichalla 
- [x] Add survey link - @danroth27 supply URL, @SteveSandersonMS add code
- [x] Add release to GitHub - @danroth27 
- [x] Push signed packages to MyGet (version `0.1.0`) - @SteveSandersonMS
- [x] Upload VSIX to VS Gallery - Upload from corpnet and assign Microsoft as the publish, add multiple owners - @danroth27
- [x] Publish FlightFinder sample to GitHub - @SteveSandersonMS
- [x] Check third-party notices, licenses, etc. - @danroth27 
- [x] Repo README updates - @danroth27 

In blog post, document known issues:

 * Currently you can't use `data-*` attributes with C#-expression values (e.g., `<div data-something=@value />` does not compile). Workaround: write `data_*` instead (e.g., `<div data_something=@value />`), and we'll render it as `data-*` in the DOM. Tracked as aspnet/Blazor#297 
 * If you create a project with a space or hyphen in the project name, the result app has build errors. Workaround: don't put spaces or hyphens in the project name. Tracked as aspnet/Blazor#291
