### ISSUE TITLE
Expose System.IO.Pipelines in ASP.NET Core

### ISSUE THREAD

**Issue by jkotalik** [aspnet/AspNetCore#3973]
- [x] Add IRequestBodyPipeFeature and IResponseBodyPipeFeature #3972
- [x] Add Pipe to Stream Adapter #3971
- [x] Add Stream to Pipe Adapter #3966
- [ ] Re-implement the FormReader on top of the PipeReader #3967
- [x] Create response body PipeWriter by decorating Kestrel's connection PipeWriter #4351

**Comment by Tratcher** [comment]
When exposing the pipes directly from the servers we'll have to consider the semantics of PipeReader/Writer.Complete, with and without an Exception.

Today servers make Stream.Dispose no-op for request and response. The server controls the lifetime.

We'll also need to redesign some of the buffering components like the one used by the form reader.

**Comment by jkotalik** [comment]
Closing as all issues are tracked separately/completed here.
