### ISSUE TITLE
[3.0.0] Breaking Change Tracking

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#5312]
This issue is to track breaking changes implemented or planned for 3.0 to ensure they get announced properly

* [ ] Minor Version property added to `IHubProtocol`
* [ ] JSON Protocol Changes (`AddJsonProtocol` to `AddNewtonsoftJsonProtocol`)
* [x] #8525 (ResetSendPing and friend removed)

**Comment by Eilon** [comment]
@anurse - is the a PRI-0 bug, and is it in the correct milestone?

**Comment by anurse** [comment]
This isn't really used anymore.

**Comment by MagicAndre1981** [comment]
@anurse 

where is a documentation for breaking changes in 3.0 final? The [SignalR page](https://docs.microsoft.com/en-US/aspnet/core/signalr/introduction?view=aspnetcore-3.0) was not updated since 2018 and misses a migration guide from 2.2 to 3.0.

What steps do I have to follow to upgrade from 2.2 to 3.0? What is changed/removed? I only know my selfhost must be now .net core 3.0 app. What else is changed?

**Comment by MagicAndre1981** [comment]
@anurse 

ok, I found [this link](https://docs.microsoft.com/en-US/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#signalr-code)

Is this all?

**Comment by anurse** [comment]
Yes, that is the migration guide for SignalR. It may not be a complete breaking change list, but it covers most of the core scenarios. A full list of breaking changes can be found in the issue tracker for [aspnet/Announcements](https://github.com/aspnet/Announcements/issues?q=is%3Aissue+is%3Aopen+label%3A%22Breaking+change%22+label%3A3.0.0) (and you can subscribe to that repo to get GitHub notifications when new breaking changes are introduced in 3.1 and beyond). Moving forward, we are also working on publishing ASP.NET Core breaking changes to the central [.NET Core Breaking Changes](https://docs.microsoft.com/en-us/dotnet/core/compatibility/breaking-changes) page on our documentation site (but we haven't completed that yet).

**Comment by MagicAndre1981** [comment]
> Moving forward, we are also working on publishing ASP.NET Core breaking changes to the central [.NET Core Breaking Changes](https://docs.microsoft.com/en-us/dotnet/core/compatibility/breaking-changes) page on our documentation site (but we haven't completed that yet).

ok, please also reply here when the link goes online.

**Comment by anurse** [comment]
I'd suggest you watch aspnet/Announcements as that's where announcements like this would be posted.
