### ISSUE TITLE
Blazor Roadmap

### ISSUE THREAD

**Issue by rynowak** [aspnet/AspNetCore#8177]
**This is a tracking item for the overall Blazor features in .NET Core 3.0**

Items are arranged by milestone. 

*DESIGN:* items mean that the design work will occur in that milestone - the actual product work will generally happen in the next milestone.

## Preview 3

- [x] [#6351](https://github.com/aspnet/AspNetCore/issues/6351) - Updates to Event Handling and Bind
- [x] [#4057](https://github.com/aspnet/AspNetCore/issues/4057) - Tooling for `.razor`
- [x] [#4054](https://github.com/aspnet/AspNetCore/issues/4054) - Startup Experience
- [x] [#5464](https://github.com/aspnet/AspNetCore/issues/5464) - Prerendering
- [x] [#5460](https://github.com/aspnet/AspNetCore/issues/5460) - Forms and Validation
- [x] [#6353](https://github.com/aspnet/AspNetCore/issues/6353) - Component lifecycle and events

## Preview 4  / VS 16.1 preview 1

*Preview 4 is a long milestone and is aligned with a VS release. Therefore we are trying to pack in as much as possible related to tooling and language*

- [x] [#4048](https://github.com/aspnet/AspNetCore/issues/4048) - *DESIGN:* Auth
- [x] [#6349](https://github.com/aspnet/AspNetCore/issues/6349) - *DESIGN:* multi-project static content
- [x] [#5545](https://github.com/aspnet/AspNetCore/issues/5545) - *DESIGN:* Control over event propagation and default actions
- [x] [#7573](https://github.com/aspnet/AspNetCore/issues/7537) - Handle reconnection to same server
- [x] [#5110](https://github.com/aspnet/AspNetCore/issues/5110) - Replacement for `@helper`
- [x] [#6392](https://github.com/aspnet/AspNetCore/issues/6392) - Define template experience for Component-only RCL
- [x] [#5577](https://github.com/aspnet/AspNetCore/issues/5577) - Components are based on `@using` instead of `@addTagHelper` 
- [x] [#5106](https://github.com/aspnet/AspNetCore/issues/5106) - Use Root Namespace from project file for components
- [x] [#6374](https://github.com/aspnet/AspNetCore/issues/6374) - _Imports.razor
- [x] [#7311](https://github.com/aspnet/AspNetCore/issues/7311) - Use Shared-Framework-allowed MessagePack serializer
- [x] #[TBD](https://github.com/orgs/aspnet/projects/19) - *Follow Up:* .razor, templates and tooling
- [x] #[TBD](https://github.com/orgs/aspnet/projects/19) - *Follow Up:* SignalR connection problems and troubleshooting
- [x] [#5092](https://github.com/aspnet/AspNetCore/issues/5092) - C#8 support in Razor

## Preview 5

*Preview 5 is a relatively short milestone and we don't expect to fix things during this time that require tooling changes*

## Preview 6

- [x] [#10393](https://github.com/aspnet/AspNetCore/issues/10393) - Support `@attribute` directive
- [x] [#6364](https://github.com/aspnet/AspNetCore/issues/6364) - Directive attributes
- [x] [#8205](https://github.com/aspnet/AspNetCore/issues/8205) - Use System.Text.Json in Components/JSInterop
- [x] [#8232](https://github.com/aspnet/AspNetCore/issues/8232) - Support `key` to guarantee preservation of element/component instances
- [x] [#5629](https://github.com/aspnet/AspNetCore/issues/5629) - Make SignalR Service usage an aspect of deployment, not source code
- [x] [#6361](https://github.com/aspnet/AspNetCore/issues/6361) - Support `@code`
- [x] [#6349](https://github.com/aspnet/AspNetCore/issues/6349) - *IMPLEMENT:* multi-project static content
- [x] [#4048](https://github.com/aspnet/AspNetCore/issues/4048) - *IMPLEMENT:* Auth

## Preview 7

*Preview 7 has a small number of actual deliverable features... we're investing the most time in some of ongoing 3.0 efforts listed in the 3.0 Tracking section*

- [x] [#5071](https://github.com/aspnet/AspNetCore/issues/5071) - Splat operator for attributes 
- [x] [#8204](https://github.com/aspnet/AspNetCore/issues/8204) - Async diffing

## Preview 8

- [x] [#9386](https://github.com/aspnet/AspNetCore/issues/9386) - Globalization support
- [x] [#7536](https://github.com/aspnet/AspNetCore/issues/7536) - RCL template offers choice between Components or MVC
- [x] [#8825](https://github.com/aspnet/AspNetCore/issues/8825) - Update visibility of component parameters 
- [x] [#9860](https://github.com/aspnet/AspNetCore/issues/9860) - Make component binding case-sensitive
- [x] [#9565](https://github.com/aspnet/AspNetCore/issues/9565) - Security review for server-side Blazor

## Preview 9

We have planned no any feature work in this milestone and we will be focusing on bug fixes only.
Some other things which we may have to handle here are potential follow-ups from security and API reviews.
- [x] [#4050](https://github.com/aspnet/AspNetCore/issues/4050) - Blazor API review

## 3.0 Tracking 

- [x] [#10472](https://github.com/aspnet/AspNetCore/issues/10472) - Server-side Blazor in production
- [x] [#10449](https://github.com/aspnet/AspNetCore/issues/10449) - Server-side Blazor E2E performance and capacity testing

## 3.1

- [ ] [#7268](https://github.com/aspnet/AspNetCore/issues/7268) - [Blazor] Add ability to pass @typeparam down to child components
- [x] [#8613](https://github.com/aspnet/AspNetCore/issues/8613) - *Follow Up:* Error handling improvements
- [ ] [#5545](https://github.com/aspnet/AspNetCore/issues/5545) - *IMPLEMENT:* Control over event propagation and default actions
- [ ] [#5487](https://github.com/aspnet/AspNetCore/issues/5487) - Components support partial classes

**TBD**

## Backlog

Items here are arranged in rough priority order.

- [ ] [#4065](https://github.com/aspnet/AspNetCore/issues/4065) - Unify Razor editor initialization with closed file infrastructure (blocks EnC, Refactoring, Partial Classes)
- [ ] [#7268](https://github.com/aspnet/AspNetCore/issues/7268) - *DESIGN:* Child Components with strong typing
- [ ] [#7268](https://github.com/aspnet/AspNetCore/issues/7268) - *IMPLEMENT:* Child Components with strong typing
- [ ] [#6348](https://github.com/aspnet/AspNetCore/issues/6348) - *DESIGN:* Enable Views/Pages to use component as elements
- [ ] [#6348](https://github.com/aspnet/AspNetCore/issues/6348) - *IMPLEMENT:* Enable Views/Pages to use component as elements
- [ ] [#8183](https://github.com/aspnet/AspNetCore/issues/8183) - Generate event handler methods in VS
- [ ] [#8214](https://github.com/aspnet/AspNetCore/issues/8214) - Component Islands
- [x] [#5471](https://github.com/aspnet/AspNetCore/issues/5471) - Localization support
- [x] [#6356](https://github.com/aspnet/AspNetCore/issues/6356) - Components VSCode support
- [ ] [#5490](https://github.com/aspnet/AspNetCore/issues/5490) - Components VS4Mac support
- [ ] [#5562](https://github.com/aspnet/AspNetCore/issues/5562) - reconnection to a different server
- [ ] ~~[#6358](https://github.com/aspnet/AspNetCore/issues/6358) - Automated eviction for circuits~~
- [ ] [#4052](https://github.com/aspnet/AspNetCore/issues/4052) - Performance infrastructure and hello world perf test
- [ ] Unit Testing
- [ ] Scaffolding

**Comment by rynowak** [comment]
Locking this because it's our high-level planning and status issue. Feel free to use other issues to discuss or give feedback.

**Comment by danroth27** [comment]
Closing as we are done with feature work for 3.0! Wohoo!
