### ISSUE TITLE
[Epic] Remove pubternal types from assemblies in the targeting pack 

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#8308]
If there is interest in applying the MVC treatment to Kestrel(#8306)  , perhaps we should more broadly discuss doing this for everything in the targeting pack prior to 3.0. 

* [x] Antiforgery
* [ ] Components
* [ ] DataProtection
* [ ] DefaultBuilder
* [ ] Hosting
* [x] Html  (no internal types)
* [ ] Http
* [ ] Identity
* [ ] Middleware
* [x] Mvc
* [ ] Security
* [x] Servers (Kestrel - https://github.com/aspnet/AspNetCore/issues/8306)
* [ ] Shared
* [ ] SignalR (https://github.com/aspnet/AspNetCore/issues/10169)
* [ ] Tools

**Comment by anurse** [comment]
Is anyone still using this issue? I know we have some sub-issues filed for key areas (SignalR, etc.) but do we still need this issue? @mkArtakMSFT @pranavkm @rynowak @davidfowl

**Comment by davidfowl** [comment]
Can we link them here? I'd like an uber tracking issue.

**Comment by anurse** [comment]
I believe the ones that exist are all linked. I don't expect we'll have resources to go through ones that don't already have issues listed.

**Comment by pranavkm** [comment]
Feel free to close this. This never got triaged \ tracked properly.
