### ISSUE TITLE
Tracking issue for System.Text.Json follow up

### ISSUE THREAD

**Issue by pranavkm** [aspnet/AspNetCore#8489]
* [ ] ~~DateTime - https://github.com/dotnet/corefx/issues/36023~~ Work around found
* [x] Dictionary<TKey, TValue> - https://github.com/dotnet/corefx/issues/36024
* [x] Collection interfaces - https://github.com/dotnet/corefx/issues/36643, https://github.com/dotnet/corefx/issues/36640
* [x] Support for camel casing (https://github.com/dotnet/corefx/issues/36351)
* [x] Support for `JsonExtensionDataAttribute` - https://github.com/dotnet/corefx/issues/36147
* [x] Support Object in deserialize - https://github.com/dotnet/corefx/issues/36167
* [x] Cyclic reference objects - https://github.com/dotnet/corefx/issues/36510
* [ ] GUID not supported (and other types) - https://github.com/dotnet/corefx/issues/36639
* [ ] Casting numbers to string on serialize - should be able to be covered by https://github.com/dotnet/corefx/issues/36639

* [ ] Error handling - https://github.com/aspnet/AspNetCore/issues/8474, https://github.com/dotnet/corefx/issues/36025

---------------

JSInterop

* [x] Support for mixed type arrays - https://github.com/dotnet/corefx/issues/36166

**Comment by pranavkm** [comment]
cc @glennc

**Comment by anurse** [comment]
@BrennanConroy can you make sure this includes any SignalR-related issues and link them here if not? I think we should try to have a single list of ASP.NET Core needs from JSON.

**Comment by BrennanConroy** [comment]
Support Object in deserialize - https://github.com/dotnet/corefx/issues/36167
Cyclic reference objects - https://github.com/dotnet/corefx/issues/36510
GUID not supported (and other types) - https://github.com/dotnet/corefx/issues/36639
Casting numbers to string on serialize - should be able to be covered by https://github.com/dotnet/corefx/issues/36639

**Comment by rynowak** [comment]
We should revisit the presence of dotnet/corefx#36023 on this list. I don't think we're testing the case that they support.

**Comment by pranavkm** [comment]
Yeah, that could be struck out. We relied on it for temp data serialization, and ended up doing our own thing. Json.NET has some pretty wide support for round-tripping things in the absence of any type information, and I don't think we should expect that of all Json serializers. @BrennanConroy I'd recommend doing something similar with your `Guid` requirements (we handle those too): https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.ViewFeatures/src/Infrastructure/DefaultTempDataSerializer.cs#L49-L62

**Comment by BrennanConroy** [comment]
If you look at the tracking issue for GUID, it's for the ability to have customization on the serializer, I think it's still valid to track

**Comment by mkArtakMSFT** [comment]
Closing this as all the blocking issues have been resolved.
