### ISSUE TITLE
[Epic] Enable automatic reconnection in SignalR clients

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8797]
We should allow users to opt-in to automatic reconnection in all of our clients. Message replay is **a non-goal for this feature at this time**.

Child Issues:
* [x] https://github.com/aspnet/AspNetCore/issues/8709 Support automatic reconnect in the TypeScript client
* ~~https://github.com/aspnet/AspNetCore/issues/8712 Support automatic reconnect in the C++ client~~ Cut for 3.0.
* ~~https://github.com/aspnet/AspNetCore/issues/8711 Support automatic reconnect in the Java client~~ Postponed to post-3.0
* [x] https://github.com/aspnet/AspNetCore/issues/8710 Support automatic reconnect in the .NET client (**3.0.0-preview6**)
* [x] https://github.com/aspnet/AspNetCore/issues/6434 Error parsing handshake response during reconnect
* ~~https://github.com/aspnet/AspNetCore/issues/9016 Add ReconnectPolicyBuilder to SignalR TS client~~ Cut, waiting for customer feedback. Not necessary for 3.0.
* ~~https://github.com/aspnet/AspNetCore/issues/9017 Allow IReconnectPolicy.nextRetryDelayInMilliseconds to return a promise in the SignalR TS client~~  Cut, waiting for customer feedback. Not necessary for 3.0.
