### ISSUE TITLE
[Epic] ANCM Improvements

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8833]
There are a number of improvements we want to make to ANCM in-proc in 3.0 that relate to improved integration with the .NET Core host and Azure App Service.

Child Items:
* [x] https://github.com/aspnet/AspNetCore/issues/5153 ANCM In process: Managed exceptions before full initialization are too hard to look at
* [x] https://github.com/aspnet/AspNetCore/issues/8001 React to semver v2 support change in core-setup
* [x] https://github.com/aspnet/AspNetCore/issues/7307 Change runtime SiteExtension to replace AspNetCoreModuleV2 definition
* [x] https://github.com/aspnet/AspNetCore/issues/9667 Do not capture startup errors in Hosting when running in IIS
* ~~https://github.com/aspnet/AspNetCore/issues/8838 React to hostfxr locating logic~~ Cut from 3.0
* [x] https://github.com/aspnet/AspNetCore/issues/10011 [ANCM] [in proc] Write pre-main errors to the browser when running in development
* [x] https://github.com/aspnet/AspNetCore/issues/9394 Increase stack size for host when running in IIS In-Proc
* [x] https://github.com/aspnet/AspNetCore/issues/9520 Use runtime property settings instead of environment variables for setting startup hook
* [x] https://github.com/aspnet/AspNetCore/issues/10005 [ANCM] [out of process] Write stdout to EventLog when exit code is non-zero
* [x] https://github.com/aspnet/AspNetCore/issues/9873 [ANCM In-proc] Improve handling of malformed warmup requests
* [x] https://github.com/aspnet/AspNetCore/issues/10008 Create new IIS sub-status code handler load failure

Tracking issues/PRs in coreclr/core-setup
* [x] https://github.com/dotnet/coreclr/issues/23343 Need this for #5153 
* [x] https://github.com/dotnet/coreclr/pull/23178 Need this for #5153 to set environment variables for IIS

**Comment by anurse** [comment]
@jkotalik to review and see if there's anything related to .NET Core host integration that isn't covered here.

**Comment by shirhatti** [comment]
EDIT: Added #9667 as a child item
