### ISSUE TITLE
[Epic] ASP.NET Core should support distributed tracing

### ISSUE THREAD

**Issue by anurse** [aspnet/AspNetCore#8924]
We should provide integration with distributed tracing work going on throughout .NET.

Child Items:
* [x] https://github.com/aspnet/AspNetCore/issues/5926 Ambient distributed tracing context
* [x] https://github.com/aspnet/AspNetCore/issues/5925 Support W3C format for distributed trace context propagation
* [x] https://github.com/aspnet/AspNetCore/issues/5918 Parent Request Id is mislabeled as Correlation Id in log scope
*  ~~https://github.com/aspnet/AspNetCore/issues/5927 Use TraceIdentifier of HttpContext as a span in W3C when possible~~ cut from 3.0
* ~~https://github.com/aspnet/AspNetCore/issues/5914 Add a way to configure the IHttpRequestIdentifierFeature to read a configurable header~~ cut from 3.0
* ~~https://github.com/aspnet/AspNetCore/issues/5928 Serialize response context as a response header~~ cut from 3.0

**Comment by anurse** [comment]
Note: we don't really have resources allocated to this right now.

cc @glennc

**Comment by davidfowl** [comment]
I don't think we need to do all of these as part of the epic. We should meet with @lmolkova next week and narrow down the items to the MVP.
