### ISSUE TITLE
Security review for Blazor

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/AspNetCore#9565]
## Threat Models

- [X] [Client](https://github.com/aspnet/specs/blob/master/notes/3_0/blazor_client_security.md)
- [x] [Server](https://github.com/aspnet/specs/blob/master/notes/3_0/blazor_server_security.md)

Documents will be made public when review is complete.

## Client Action Items

- [x] Investigate CSP for *bootstrapping*
- [x] Investigate providing a default CORS configuration.
- [x] Follow up on the need for CSRF once browser support is locked

## Server Action Items

- [x] Investigate turning on CSP in our default layouts. (require same-origin)
  - Investigation is done, pending a decission on whether we add it or not.
  - We decided not to use CSP due to usability concerns.
- [x] Security review of embedded files.
  - Notes about security sent to the stakeholders.
- [ ] Provide documentation and guidance for responsible use of JS -> .NET interop in the server-side model. (JS interop is untrusted input)
- [x] Security code review for JS interop.
- [x] Add default timeouts for JS interop async calls.
  - [x] JSInterop library work
  - [x] Blazor server-side work
- [x] Sanitize JS interop exceptions (generic errors).
  - [x] JSInterop library work
  - [x] Blazor server-side work
- [X] Generate CircuitIds that are not guessable/tamperable.
- [x] Validate the same user identity/browser session when allowing a client to join a Circuit.
  - Only concern here was scale out + cookie, but it should be doable thanks to the new signalr stickyness.
  - Follow up with tooling to enable signalr stickiness by default when deploying to Azure.
- [x] Investigate securing websockets for cross-origin access.
  * We are not doing anything by default, simply providing guidance, covered as part of https://github.com/aspnet/AspNetCore.Docs/issues/12995
- [x] Security code review for Message Pack + Blazor Pack
- [x] Security code review for render tree serialization
- [x] Show and tell with Auth for @blowdart
  - @SteveSandersonMS is on point for this.
- [ ] Measure and mitigate risk of opening too many circuits
  - [ ] Add limits to the amount of queued pending renders. https://github.com/aspnet/AspNetCore/issues/11964
  - [ ] Add timeouts for idle circuits. https://github.com/aspnet/AspNetCore/issues/11965
  - [ ] Provide guidance on how to limit the number of opened circuits per user. https://github.com/aspnet/AspNetCore/issues/11966
  - [ ] Prevent start circuit from creating multiple circuits under any circumstance. https://github.com/aspnet/AspNetCore/issues/12054
  - [ ] Ensure appropriate memory thresholds under heavy event loads. https://github.com/aspnet/AspNetCore/issues/12003
- [ ] Sanitize unhandled exceptions on ComponentHub https://github.com/aspnet/AspNetCore/issues/12055
- [ ] Incorrect batch acks should not produce warnings. https://github.com/aspnet/AspNetCore/issues/12056
- [ ] Passing invalid parameters to StartCircuit should not produce exceptions. https://github.com/aspnet/AspNetCore/issues/12057 
- [ ] Convert ids for events and components into `long`. https://github.com/aspnet/AspNetCore/issues/12058

**Comment by javiercn** [comment]
We've done all the work we wanted to do here. We've met several times with the appropriate people to look at the different security aspects involved in server side blazor.

The remaining action items are tracked in separate issues and the last piece is to put together the meeting notes we collected during the reviews and put them in a consistent way as part of the security guidance doc for blazor server-side applications https://github.com/aspnet/AspNetCore.Docs/issues/12995

@mkArtakMSFT I'm not sure if we should just close this issue at this point.

**Comment by rynowak** [comment]
There's a bunch of items that are not checked off. Check them off if they are done, or strike them out if a note if we didn't do it 😆 

Did you update the threat model with the additional stuff?

**Comment by mkArtakMSFT** [comment]
Looks like all the `unchecked items` except one have additional tracking items. Please either create one more tracking item for the following one or simply strike it through (to be explicit that we didn't do it, neither we plan to):

> Provide documentation and guidance for responsible use of JS -> .NET interop in the server-side model. (JS interop is untrusted input)

And yes, as @rynowak said, update teh threat model with additional stuff, based on all the findings. Then this can be closed.
